"""add_output_templates_table

Revision ID: 8d050963af48
Revises: 0002
Create Date: 2026-05-20 11:55:42.039923+08:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '8d050963af48'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_md', sa.Text(), nullable=True),
    sa.Column('generator_code', sa.Text(), nullable=True),
    sa.Column('sample_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_output_templates_name', 'output_templates', ['name'], unique=False)
    op.alter_column('scan_tasks', 'confidence_avg',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('scan_tasks', 'structure_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_tasks', 'structure_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('scan_tasks', 'confidence_avg',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.drop_index('idx_output_templates_name', table_name='output_templates')
    op.drop_table('output_templates')
    # ### end Alembic commands ###
